---
title: "Cours n°01"
subtitle: "Introduction à l'inférence bayésienne"
date: 2022-10-11
toc: false
lang: fr
---

## En préparation du cours

- Installer les paquets `R` : voir page [installation](../install.qmd).
- (*optionnel*) Lire le premier chapitre de {{< fa book >}} *Statistical Rethinking*.

## Slides

Les slides de ce cours sont disponibles ci-dessous. Vous pouvez naviguer dans ces slides avec <kbd>←</kbd> et <kbd>→</kbd>. Si vous tapez <kbd>h</kbd> vous verrez apparaître un ensemble de commandes spécifiques à la lecture de ces slides (e.g., <kbd>f</kbd> pour passer en plein écran). Vous pouvez aussi télécharger une version PDF des slides ou le code du cours en cliquant sur un des boutons ci-dessous.

<p class="buttons" style="text-align:center;"><a class="btn btn-danger" target="_blank" href="../slides/html/cours01.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> Voir les slides en ligne </a> <a class="btn btn-danger" target="_blank" href="../slides/pdf/cours01.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Télécharger la version PDF </a> <a class="btn btn-danger" target="_blank" href="../slides/code/cours01.R"><i class="fa-solid fa-code"></i> Télécharger le code </a> </p>

<div class="ratio ratio-16x9"> <iframe src="../slides/html/cours01.html"></iframe> </div>

::: {.callout-tip}
Voir toutes les commandes de `revealjs` en appuyant sur <kbd>m</kbd> puis <kbd>h</kbd>.
:::

## Pour aller plus loin

- Hájek, A. (2019). Interpretations of probability. In E. N. Zalta (Ed.), The stanford encyclopedia of philosophy (Fall 2019). Metaphysics Research Lab, Stanford University. <https://plato.stanford.edu/archives/fall2019/entries/probability-interpret/>
- 3Blue1Brown (Director). (2019, December 22). Bayes theorem, the geometry of changing beliefs. <https://www.youtube.com/watch?v=HZGCoVF3YvM>
