---
title: "Course n°03"
subtitle: "Markov Chain Monte Carlo, generalised linear model"
date: 2023-12-01
toc: false
lang: en
---

## To be done ahead of this course

- Check previous courses.
- (*optional*) Read chapters 5, 10, and 11 from {{< fa book >}} *Statistical Rethinking*.

## Slides

Slides for this course are available below. You can navigate these sides using the <kbd>←</kbd> and <kbd>→</kbd> keys. Pressing <kbd>m</kbd> will display all commands you can use (e.g., <kbd>f</kbd> to switch to full screen mode). You can also download a PDF version of these slides or the `R` code associated with these slides by clicking on the buttons below.

<p class="buttons" style="text-align:center;"><a class="btn btn-danger" target="_blank" href="../slides/html/cours03.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> Read the slides online </a> <a class="btn btn-danger" target="_blank" href="../slides/pdf/cours03.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download the PDF version </a> <a class="btn btn-danger" target="_blank" href="../slides/code/cours03.R"><i class="fa-solid fa-code"></i> Download the R code </a> </p>

<div class="ratio ratio-16x9"> <iframe src="../slides/html/cours03.html"></iframe> </div>

::: {.callout-tip}
See all `revealjs` commands by pressing <kbd>m</kbd> then <kbd>h</kbd>.
:::

## To go further

- Betancourt, M. (2018). A Conceptual Introduction to Hamiltonian Monte Carlo (arXiv:1701.02434). arXiv. <https://arxiv.org/abs/1701.02434>
- Feng, C. (2022). Chi-feng/mcmc-demo [JavaScript]. <https://github.com/chi-feng/mcmc-demo> / <https://chi-feng.github.io/mcmc-demo/>
- Dogucu, A. A. J., Miles Q., & Ott, Mine. (2022). Chapter 7 - MCMC under the Hood. In Bayes Rules! An Introduction to Applied Bayesian Modeling. Available online at: <https://www.bayesrulesbook.com/chapter-7.html>.
- Nalborczyk, L. (2018). Using R to make sense of the generalised linear model. Blogpost available at <https://www.barelysignificant.com/post/glm/>.
