---
title: "Course n°01"
subtitle: "Introduction to Bayesian inference, Beta-Binomial model"
date: 2023-11-30
toc: false
lang: en
---

## To be done ahead of this course

- Install `R` packages: see the [installation](../install.qmd) page.
- Verify everything is correctly installed via `imsb::check_install()`.
- (*optional*) Read chapters 1-3 from {{< fa book >}} *Statistical Rethinking*.

## Slides

Slides for this course are available below. You can navigate these sides using the <kbd>←</kbd> and <kbd>→</kbd> keys. Pressing <kbd>m</kbd> will display all commands you can use (e.g., <kbd>f</kbd> to switch to full screen mode). You can also download a PDF version of these slides or the `R` code associated with these slides by clicking on the buttons below.

<p class="buttons" style="text-align:center;"><a class="btn btn-danger" target="_blank" href="../slides/html/course01.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> Read the slides online </a> <a class="btn btn-danger" target="_blank" href="../slides/pdf/course01.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download the PDF version </a> <a class="btn btn-danger" target="_blank" href="../slides/code/cours01.R"><i class="fa-solid fa-code"></i> Download the R code </a> </p>

<div class="ratio ratio-16x9"> <iframe src="../slides/html/course01.html"></iframe> </div>

::: {.callout-tip}
See all `revealjs` commands by pressing <kbd>m</kbd> then <kbd>h</kbd>.
:::

## To go further

- Hájek, A. (2019). Interpretations of probability. In E. N. Zalta (Ed.), The stanford encyclopedia of philosophy (Fall 2019). Metaphysics Research Lab, Stanford University. <https://plato.stanford.edu/archives/fall2019/entries/probability-interpret/>
- 3Blue1Brown (Director). (2019, December 22). Bayes theorem, the geometry of changing beliefs. <https://www.youtube.com/watch?v=HZGCoVF3YvM>
- 3Blue1Brown (Director). (2020, March 15). Binomial distributions | Probabilities of probabilities, part 1. <https://www.youtube.com/watch?v=8idr1WZ1A7Q>
- 3Blue1Brown (Director). (2020, April 12). Why "probability of 0" does not mean "impossible" | Probabilities of probabilities, part 2. <https://www.youtube.com/watch?v=ZA4JkHKZM50>
