---
title: "Course n°02"
subtitle: "Introduction to brms, linear regression"
date: 2023-11-30
toc: false
lang: en
---

## To be done ahead of this course

- Check previous courses.
- (*optional*) Read chapters 4-6 from {{< fa book >}} *Statistical Rethinking*.

## Slides

Slides for this course are available below. You can navigate these sides using the <kbd>←</kbd> and <kbd>→</kbd> keys. Pressing <kbd>m</kbd> will display all commands you can use (e.g., <kbd>f</kbd> to switch to full screen mode). You can also download a PDF version of these slides or the `R` code associated with these slides by clicking on the buttons below.

<p class="buttons" style="text-align:center;"><a class="btn btn-danger" target="_blank" href="../slides/html/course02.html"><i class="fa-solid fa-arrow-up-right-from-square"></i> Read the slides online </a> <a class="btn btn-danger" target="_blank" href="../slides/pdf/course02.pdf" role="button"><i class="fa-solid fa-file-pdf"></i> Download the PDF version </a> <a class="btn btn-danger" target="_blank" href="../slides/code/course02.R"><i class="fa-solid fa-code"></i> Download the R code </a> </p>

<div class="ratio ratio-16x9"> <iframe src="../slides/html/course02.html"></iframe> </div>

::: {.callout-tip}
See all `revealjs` commands by pressing <kbd>m</kbd> then <kbd>h</kbd>.
:::

## To go further

- Heiss, A. (2022). Visualizing the differences between Bayesian posterior predictions, linear predictions, and the expectation of posterior predictions. Blogpost available at <https://www.andrewheiss.com/blog/2022/09/26/guide-visualizing-types-posteriors/>.
- McElreath, R. (2021). Science Before Statistics: Causal Inference. Conference recording available at <https://www.youtube.com/watch?v=KNPYUVmY3NM>.
