# (APPENDIX) Annexes {-}

# Glossaire {#glossaire}

**Affirmation du conséquent** : Raisonnement fallacieux qui consiste à inférer la réalisation d'un antécédent sur la base de la réalisation du conséquent.

**Facteur de Bayes (Bayes factor)** : Support relatif fourni par un jeu de données pour deux hypothèses alternatives. Si on considère deux hypothèses $\mathcal{H}_{1}$ et $\mathcal{H}_{2}$ et des données $x$, alors le facteur de Bayes est $p(x \given \mathcal{H}_{1}) / p(x \given \mathcal{H}_{2})$. Ce dernier peut-être interprété comme un "facteur de mise à jour" du rapport des chances a priori (i.e., avant de prendre connaissance des données) vers le rapport des chances a posteriori (i.e., après avoir pris connaissance des données).

**Négation de l'antécédent** : Raisonnement fallacieux qui consiste à affirmer une négation du conséquent sur la base d'une négation de l'antécédent.

**Probabilité** : Une valeur numérique comprise entre 0 et 1 respectant les règles du calcul probabiliste (cf. Chapitre 1).

**Règle de la somme**: Pour deux évènements $A$ et $B$, la règle de la somme nous dit que : $\Pr(A \cup B) = \Pr(A) + \Pr(B) - \Pr(A \cap B)$.

**Règle du produit**: Pour deux évènements $A$ et $B$, la règle du produit nous dit que : $\Pr(A, B) = \Pr(B) \times \Pr(A \given B) = \Pr(A) \times \Pr(B \given A)$.

**Vraisemblance (likelihood)** : Une mesure du support fourni par les données pour certaines valeurs de paramètres. Après avoir observé des données $x$ (i.e., lorsque $x$ est fixe), peut être vu comme la fonction vraisemblance $\mathcal{L}(\theta \given x)$ du paramètre $\theta$ (i.e., $p(X = x \given \theta)$.
